-- Your SQL goes here
create table roles(
    id integer primary key generated by default as identity,
    code varchar(64) not null unique,
    name varchar(128) not null,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL 
);