-- Your SQL goes here
create table users_roles(
    id integer primary key generated by default as identity,
    user_id integer NOT NULL REFERENCES users(id),
    role_id integer NOT NULL REFERENCES roles(id) 
);